### ISSUE TITLE
Remove .bot file and replace with .env

### ISSUE THREAD

**Issue by KatieProchilo** [lucashuet93/botbuilder-proactivemessaging#24]
Bot files are now [deprecated](https://docs.microsoft.com/en-us/azure/bot-service/bot-file-basics?view=azure-bot-service-4.0&tabs=js):

> Prior to the Bot Framework SDK 4.3 release, we offered the .bot file as a mechanism to manage resources. However, going forward we recommend that you use appsettings.json or .env file for managing these resources. Bots that use .bot file will continue to work for now even though the .bot file has been ***deprecated***. If you've been using a .bot file to manage resources, follow the steps that apply to migrate the settings.

The bot file should be removed and replaced with instructions on running the bot with a .env file:

```
botFilePath="./basic.bot"
botFileSecret=""
```

Partially solves #16 .

**Comment by MarekLani** [comment]
Will investigate on C# side, if there are any changes needed in regards of this deprecation
