### ISSUE TITLE
Need a brief intro for why/what/when we use proactive messages

### ISSUE THREAD

**Issue by ryanvolum** [lucashuet93/botbuilder-proactivemessaging#9]
Before jumping into the _how_ I think we'll want to address the why/what/when first. I'm happy to PR something in!

**Comment by MarekLani** [comment]
Sorry for delay, I am starting to work on the intro read.me where this will be discussed

**Comment by MarekLani** [comment]
@ryanvolum @lucashuet93  https://github.com/lucashuet93/botbuilder-proactivemessaging/pull/22

**Comment by ryanvolum** [comment]
Resolved with #22 and #18
